Expand query for virtual product
opendatacube/odc-stats pull request #96
Opened 2023-06-30 04:01 UTC by emmaai

- to reuse `_find_dss` in virtual product
- pin `datacube <= 1.8.13` because of the issue in `1.8.14`

2023-07-04 00:50 UTC, SpacemanPaul requested changes
Good refactor, but a little more documentation (and/or validation) would be helpful.

Also this patch has only has like 12% coverage. A quick coverage run of  `find_dss` with mocks should be fairly quick to throw together.

2023-07-04 00:50 UTC, SpacemanPaul commented on odc/stats/tasks.py
> +
I don't understand what's going on here.  What is the expected format of "products"?  That's some weird stuff going on with pluses and minuses.  

`products="prod1+prod2-prod3+prod4"` and `products="+++prod1+prod2-+-prod3++prod4"` both  yield the same 4 member `product_list`, but one givess a `group_size` of 4 and the other 7??  With no warning/error message?

It seems like the main purpose of `find_dss` is to expand a product string into a product list, so a little bit of documentation here would be helpful.

(It's still better than it was, mind you.)

2023-07-04 00:50 UTC, SpacemanPaul commented on odc/stats/tasks.py
> +    def _find_dss(
Having `_find_dss` and `_get_dss` side by side like this is potentially confusing.

2023-07-04 00:50 UTC, SpacemanPaul commented on setup.cfg
> +    datacube<=1.8.13
As this issue has been fixed in develop and will therefore definitely be fixed in 1.8.15, maybe just require `!=1.8.14`

2023-07-11 00:13 UTC, SpacemanPaul approved these changes
The product string splitter could do with a just a bit more documentation (specifically around the "grouping" concept).  Otherwise looking great. Thanks Emma.

2023-07-11 00:13 UTC, SpacemanPaul commented on odc/stats/tasks.py
> +            """
This is much better but I still don't understand the difference between + and - as a separator or what the significance of `group_size` is.

2023-07-11 02:50 UTC, emmaai commented on odc/stats/tasks.py
> +            """
I'll throw in a small segment in readme in next pr. It's meant to support the concept of `juxtapose` and `collate` as well as the similar idea in `odc-stats` with the same set of code.

2023-07-11 02:51 UTC, merged